jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    resource_class: 2xlarge
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14